<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOwZYPgG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOwZYPgG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOwZYPgG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOwZYPgG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOwZYPgG\App_KernelDevDebugContainer([
    'container.build_hash' => 'OwZYPgG',
    'container.build_id' => '8c9db785',
    'container.build_time' => 1625487011,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOwZYPgG');
