<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWkRetNf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWkRetNf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWkRetNf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWkRetNf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWkRetNf\App_KernelDevDebugContainer([
    'container.build_hash' => 'WkRetNf',
    'container.build_id' => '4b836a01',
    'container.build_time' => 1625488586,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWkRetNf');
