<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRslhRee\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRslhRee/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRslhRee.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRslhRee\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRslhRee\App_KernelDevDebugContainer([
    'container.build_hash' => 'RslhRee',
    'container.build_id' => 'adfbe23e',
    'container.build_time' => 1624985098,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRslhRee');
