<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'annonce_admin' => [[], ['_controller' => 'App\\Controller\\AnnonceAdminController::index'], [], [['text', '/annonce/admin']], [], []],
    'annonces_index' => [[], ['_controller' => 'App\\Controller\\AnnonceController::index'], [], [['text', '/annonces']], [], []],
    'annonce_view' => [['id'], ['_controller' => 'App\\Controller\\AnnonceController::viewAnnonce'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/view']], [], []],
    'create_annonce' => [[], ['_controller' => 'App\\Controller\\AnnonceController::createAnnonce'], [], [['text', '/annonce/new']], [], []],
    'edit_annonce' => [['id'], ['_controller' => 'App\\Controller\\AnnonceController::editAnnonce'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/edit']], [], []],
    'delete_annonce' => [['id'], ['_controller' => 'App\\Controller\\AnnonceController::deleteAnnonce'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete']], [], []],
    'annonce_list' => [[], ['_controller' => 'App\\Controller\\AnnonceController::listAnnonce'], [], [['text', '/list']], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'task' => [[], ['_controller' => 'App\\Controller\\TaskController::new'], [], [['text', '/task']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
